from uuid import UUID

from pydantic import BaseModel, ConfigDict

from app.application.ai_job_contracts import (
    SHA256_HEX_PATTERN,
    AIJobPayload,
    AIJobQueueMessage,
    AIJobType,
    AIWorkerUpdate,
    AIWorkerUpdateStatus,
    AnalyzeAnswerPayload,
    AnalyzeAnswerQueueMessage,
    AnalyzeSessionPayload,
    AnalyzeSessionQueueMessage,
    AnswerAnalysisCompletedPayload,
    AnswerAnalysisCompletedWorkerUpdate,
    ArtifactRef,
    AssetInput,
    AudioAssetInput,
    BaseAIJobQueueMessage,
    BaseAIWorkerUpdate,
    CancelledPayload,
    CancelledWorkerUpdate,
    CompletedPayload,
    CompletedWorkerUpdate,
    EraseAIDataPayload,
    EraseAIDataQueueMessage,
    ErasureCompletedPayload,
    ErasureCompletedWorkerUpdate,
    ErasureScope,
    FailedPayload,
    FailedWorkerUpdate,
    FollowUpQuestion,
    GenerateReportPayload,
    GenerateReportQueueMessage,
    Limitation,
    PrimaryQuestion,
    ProgressPayload,
    ProgressWorkerUpdate,
    ReportCompletedPayload,
    ReportCompletedWorkerUpdate,
    RubricRef,
    SessionAnalysisCompletedPayload,
    SessionAnalysisCompletedWorkerUpdate,
    SpeakerMapping,
    StartedPayload,
    StartedWorkerUpdate,
    TypedAIJobQueueMessage,
    get_completed_payload_model,
    get_completed_update_model,
    get_job_payload_model,
    parse_completed_payload,
    parse_job_payload,
    parse_queue_message,
    parse_worker_update,
)
from app.domain.session_workflow.enums.job_status import AnalysisJobStatus


class AIJobStatusResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: UUID
    job_id: UUID
    status: AnalysisJobStatus
    last_update_sequence: int
    cancel_requested: bool


__all__ = [
    "AIJobStatusResponse",
    "SHA256_HEX_PATTERN",
    "AIJobPayload",
    "AIJobQueueMessage",
    "AIJobType",
    "AIWorkerUpdate",
    "AIWorkerUpdateStatus",
    "AnalyzeAnswerPayload",
    "AnalyzeAnswerQueueMessage",
    "AnalyzeSessionPayload",
    "AnalyzeSessionQueueMessage",
    "AnswerAnalysisCompletedPayload",
    "AnswerAnalysisCompletedWorkerUpdate",
    "ArtifactRef",
    "AssetInput",
    "AudioAssetInput",
    "BaseAIJobQueueMessage",
    "BaseAIWorkerUpdate",
    "CancelledPayload",
    "CancelledWorkerUpdate",
    "CompletedPayload",
    "CompletedWorkerUpdate",
    "EraseAIDataPayload",
    "EraseAIDataQueueMessage",
    "ErasureCompletedPayload",
    "ErasureCompletedWorkerUpdate",
    "ErasureScope",
    "FailedPayload",
    "FailedWorkerUpdate",
    "FollowUpQuestion",
    "GenerateReportPayload",
    "GenerateReportQueueMessage",
    "Limitation",
    "PrimaryQuestion",
    "ProgressPayload",
    "ProgressWorkerUpdate",
    "ReportCompletedPayload",
    "ReportCompletedWorkerUpdate",
    "RubricRef",
    "SessionAnalysisCompletedPayload",
    "SessionAnalysisCompletedWorkerUpdate",
    "SpeakerMapping",
    "StartedPayload",
    "StartedWorkerUpdate",
    "TypedAIJobQueueMessage",
    "get_completed_payload_model",
    "get_completed_update_model",
    "get_job_payload_model",
    "parse_completed_payload",
    "parse_job_payload",
    "parse_queue_message",
    "parse_worker_update",
]
