from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from app.domain.session_workflow.enums.attempt_status import AnalysisAttemptStatus
from app.domain.session_workflow.enums.session_status import SessionStatus


class RubricSpec(BaseModel):
    rubric_id: str = "startup_pitch"
    version: int = 1


class ProblemDetails(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: str = Field(..., description="A URI reference that identifies the problem type.")
    title: str = Field(..., description="A short, human-readable summary of the problem type.")
    status: int = Field(..., description="The HTTP status code generated by the origin server.")
    detail: str = Field(
        ..., description="A human-readable explanation specific to this occurrence of the problem."
    )
    instance: str = Field(
        ..., description="A URI reference that identifies the specific occurrence of the problem."
    )
    code: str = Field(..., description="A stable error code string.")
    trace_id: str | None = Field(
        default=None, description="A unique trace identifier for correlation."
    )


class SessionManifestResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: UUID
    session_id: UUID
    presentation_version_id: UUID
    supporting_document_version_ids: list[UUID] = Field(default_factory=list)
    rubric_id: str = "startup_pitch"
    rubric_version: int = 1
    snapshot: dict[str, Any] | None = None
    frozen_at: datetime | None = None


class PracticeSessionResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: UUID
    project_id: UUID
    created_by: UUID
    name: str | None
    status: SessionStatus
    version: int
    created_at: datetime
    updated_at: datetime
    manifest: SessionManifestResponse | None = None
    rubric: RubricSpec = Field(default_factory=RubricSpec)


class CreatePracticeSessionRequest(BaseModel):
    name: str | None = Field(default="Practice Session", max_length=200)
    presentation_asset_version_id: UUID | None = None
    presentation_asset_id: UUID | None = None
    supporting_document_version_ids: list[UUID] = Field(default_factory=list, max_length=5)
    document_asset_ids: list[UUID] | None = None
    policy_version: str | int | None = None
    rubric: RubricSpec = Field(default_factory=RubricSpec)

    @field_validator("name", mode="before")
    @classmethod
    def set_default_name(cls, v: Any) -> str:
        if v is None or not str(v).strip():
            return "Practice Session"
        return str(v).strip()

    @field_validator("supporting_document_version_ids")
    @classmethod
    def validate_supporting_documents(cls, v: list[UUID]) -> list[UUID]:
        if len(v) != len(set(v)):
            raise ValueError("Supporting document versions cannot contain duplicates.")
        if len(v) > 5:
            raise ValueError("Supporting document versions cannot exceed 5 items.")
        return v

    @model_validator(mode="after")
    def validate_presentation_target(self) -> "CreatePracticeSessionRequest":
        if self.presentation_asset_version_id is None and self.presentation_asset_id is None:
            raise ValueError(
                "Either presentation_asset_version_id or presentation_asset_id must be provided."
            )
        return self


class UpdatePracticeSessionRequest(BaseModel):
    name: str | None = Field(default=None, min_length=1, max_length=200)
    presentation_asset_version_id: UUID | None = None
    presentation_asset_id: UUID | None = None
    supporting_document_version_ids: list[UUID] | None = Field(default=None, max_length=5)
    document_asset_ids: list[UUID] | None = None
    rubric: RubricSpec | None = None

    @field_validator("supporting_document_version_ids")
    @classmethod
    def validate_supporting_documents(cls, v: list[UUID] | None) -> list[UUID] | None:
        if v is not None:
            if len(v) != len(set(v)):
                raise ValueError("Supporting document versions cannot contain duplicates.")
            if len(v) > 5:
                raise ValueError("Supporting document versions cannot exceed 5 items.")
        return v


class PracticeSessionListResponse(BaseModel):
    items: list[PracticeSessionResponse]
    next_cursor: str | None = None


class AnalysisAttemptResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: UUID
    session_id: UUID
    status: AnalysisAttemptStatus
    created_at: datetime
    attempt_number: int
    version: int
    idempotency_key: str | None = None


class ConsentRequest(BaseModel):
    accepted: bool
    policy_version: int = Field(ge=1)


class CreateAnalysisAttemptRequest(BaseModel):
    consent: ConsentRequest


class AnalysisAttemptListResponse(BaseModel):
    items: list[AnalysisAttemptResponse]
    next_cursor: str | None = None


class CancelPracticeSessionRequest(BaseModel):
    reason: str | None = Field(
        default=None,
        max_length=500,
    )
