"""add failed_at to analysis attempts

Revision ID: 13b7d8c79976
Revises: d0bab208d7c4
Create Date: 2026-09-12 23:28:12.656485
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "13b7d8c79976"
down_revision: str | Sequence[str] | None = "d0bab208d7c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analysis_attempts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analysis_attempts", schema=None) as batch_op:
        batch_op.drop_column("failed_at")

    # ### end Alembic commands ###
