"""add email invitation

Revision ID: a58101e6379c
Revises: edf3ff11ceff
Create Date: 2026-09-07 20:06:54.920386
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a58101e6379c"
down_revision: str | Sequence[str] | None = "edf3ff11ceff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("token_hash", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "accepted", "revoked", "expired", name="invitationstatus"),
            nullable=False,
        ),
        sa.Column(
            "delivery_status",
            sa.Enum("queued", "accepted_by_gmail", "failed", name="deliverystatus"),
            nullable=False,
        ),
        sa.Column("delivery_attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "invitation_idempotency_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("invitation_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["invitation_id"],
            ["team_invitations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "key", name="uq_invitation_idempotency_team_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invitation_idempotency_keys")
    op.drop_table("team_invitations")
    # ### end Alembic commands ###
