"""add resend idomkey table

Revision ID: b5af41259a43
Revises: c06eb23ba31c
Create Date: 2026-09-08 21:01:55.353060
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b5af41259a43'
down_revision: str | Sequence[str] | None = 'c06eb23ba31c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_resend_idempotency',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('invitation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['team_invitations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('key', name='uq_invitation_resend_idempotency_key')
    )
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_table('invitation_resend_idempotency')
    # ### end Alembic commands ###
