"""remove invitation idompotancy table

Revision ID: c06eb23ba31c
Revises: a58101e6379c
Create Date: 2026-09-08 08:00:29.108351
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c06eb23ba31c"
down_revision: str | Sequence[str] | None = "a58101e6379c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invitation_idempotency_keys")
    op.add_column(
        "team_invitations", sa.Column("idempotency_key", sa.String(length=255), nullable=False)
    )
    op.create_unique_constraint(None, "team_invitations", ["idempotency_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_team_invitations_idempotency_key", "team_invitations", type_="unique")
    op.drop_column("team_invitations", "idempotency_key")
    op.create_table(
        "invitation_idempotency_keys",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("team_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("key", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("invitation_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["invitation_id"],
            ["team_invitations.id"],
            name=op.f("invitation_idempotency_keys_invitation_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("invitation_idempotency_keys_team_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("invitation_idempotency_keys_pkey")),
        sa.UniqueConstraint(
            "team_id",
            "key",
            name=op.f("uq_invitation_idempotency_team_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
