"""add email version

Revision ID: c210932aac79
Revises: 0989108a15b1
Create Date: 2026-09-10 14:54:10.474849
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c210932aac79"
down_revision: str | Sequence[str] | None = "0989108a15b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("team_invitations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "version",
                sa.Integer(),
                nullable=False,
                server_default="1",
            )
        )
        batch_op.create_foreign_key(
            "fk_team_invitations_team_id_teams",
            "teams",
            ["team_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.alter_column(
            "version",
            existing_type=sa.Integer(),
            server_default=None,
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "display_name",
            existing_type=sa.VARCHAR(length=255),
            nullable=True,
            existing_server_default=sa.text("''::character varying"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "display_name",
            existing_type=sa.VARCHAR(length=255),
            nullable=False,
            existing_server_default=sa.text("''::character varying"),
        )

    with op.batch_alter_table("team_invitations", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_team_invitations_team_id_teams",
            type_="foreignkey",
        )
        batch_op.drop_column("version")

    # ### end Alembic commands ###
