"""add_practice_session

Revision ID: d0bab208d7c4
Revises: c210932aac79
Create Date: 2026-09-12 12:49:42.410456
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d0bab208d7c4"
down_revision: str | Sequence[str] | None = "c210932aac79"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "practice_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "ready",
                "analyzing",
                "failed",
                "questions_ready",
                "questions_in_progress",
                "report_generating",
                "completed",
                "cancelled",
                name="sessionstatus",
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consent_granted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("practice_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_practice_sessions_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "session_manifests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("presentation_version_id", sa.UUID(), nullable=False),
        sa.Column("document_version_id", sa.UUID(), nullable=True),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["asset_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["presentation_version_id"],
            ["asset_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["practice_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_table(
        "analysis_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("manifest_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "failed",
                "completed",
                "cancelled",
                name="analysisattemptstatus",
            ),
            nullable=False,
        ),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["manifest_id"],
            ["session_manifests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["practice_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "attempt_number", name="uq_session_attempt_number"),
        sa.UniqueConstraint(
            "session_id", "idempotency_key", name="uq_analysis_attempt_idempotency_key"
        ),
    )
    with op.batch_alter_table("analysis_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_analysis_attempts_session_id"), ["session_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("analysis_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_attempts_session_id"))

    op.drop_table("analysis_attempts")
    op.drop_table("session_manifests")
    with op.batch_alter_table("practice_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_practice_sessions_project_id"))

    op.drop_table("practice_sessions")
    # ### end Alembic commands ###
