from typing import Protocol
from uuid import UUID

from app.domain.session_workflow.entities.qa_round import Answer, QARound, Question


class QARepository(Protocol):
    async def get_round_by_session(self, session_id: UUID) -> QARound | None: ...

    async def get_round_for_update(self, round_id: UUID) -> QARound | None: ...

    async def get_question(self, question_id: UUID) -> Question | None: ...

    async def list_questions(self, round_id: UUID) -> list[Question]: ...

    async def get_answer(self, answer_id: UUID) -> Answer | None: ...

    async def get_answer_for_update(self, answer_id: UUID) -> Answer | None: ...

    async def get_answer_by_question(self, question_id: UUID) -> Answer | None: ...

    async def list_answers(self, round_id: UUID) -> list[Answer]: ...

    async def create_round(self, round_: QARound) -> None: ...

    async def create_questions(self, questions: list[Question]) -> None: ...

    async def create_answer(self, answer: Answer) -> None: ...

    async def update_round(self, round_: QARound, expected_version: int) -> None: ...

    async def update_question(self, question: Question) -> None: ...

    async def update_answer(self, answer: Answer) -> None: ...
